# Input/Output settings
input:
  target_filename: orthomosaic_visible.tif

# Image preprocessing settings
downscaling:
  target_size: [4096, 4096]
  chunk_size: 4096
  overlap: 128
  num_workers: 10

# Segmentation settings
segmentation:
  sam_target_size: [1024, 1024]
  min_segment_size: 0.004
  pixel_value_threshold: 0.3
  max_nodata_percentage: 0.00025
  outlier_threshold: -1.3
  border_size: 10
  nodata_value: [255, 255, 255, 0]

  # Initial segmentation settings
  thresholded_settings:
    sam_checkpoint: "PRE_PROCESS/SEGMENTATION/sam_vit_b_01ec64.pth"
    model_type: "vit_b"
    points_per_side: 32
    pred_iou_thresh: 0.08
    stability_score_thresh: 0.8
    box_nms_thresh: 0.4
    crop_nms_thresh: 0.4
    crop_n_layers: 0
    
  # Fallback segmentation settings
  unprocessed_settings:
    sam_checkpoint: "PRE_PROCESS/SEGMENTATION/sam_vit_b_01ec64.pth"
    model_type: "vit_b"
    points_per_side: 32
    pred_iou_thresh: 0.08
    stability_score_thresh: 0.8
    box_nms_thresh: 0.6
    crop_nms_thresh: 0.6
    crop_n_layers: 1

# Processing control flags
show_masks: False
skip_enabled: False
save_debug: True
autumn_filtered: False
seed: 42