path: D:\Data\UOG_2848
output_path: data\chunks\demo\2848
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
  -
    name: orthos\data-analysis\nir.tif
    dimensions: 1
mask: D:\Data\UOG_2848\mask_2848.tif
reference: D:\Data\UOG_2848\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 8
anomaly_threshold: 0.8
scale_ratio: 0.5