path: F:\Data\UOG_1676
output_path: data\chunks\DRGB_INF_TEST\1676
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_1676-new.tif
reference: F:\Data\UOG_1676\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 8
anomaly_threshold: 0.0
scale_ratio: 0.5