path: D:\Data\UOG_1676
output_path: data\chunks\DRGB_INF\1676
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\danie\OneDrive - University of Cape Town\Uploads\mask_1676-new.tif
reference: D:\Data\UOG_1676\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_1996
output_path: data\chunks\DRGB_INF\1996
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\danie\OneDrive - University of Cape Town\Uploads\mask_1996.tif
reference: D:\Data\UOG_1996\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_1883
output_path: data\chunks\DRGB_INF\1883
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\danie\OneDrive - University of Cape Town\Uploads\mask_1883-2.tif
reference: D:\Data\UOG_1883\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2057
output_path: data\chunks\DRGB_INF\2057
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\danie\OneDrive - University of Cape Town\Uploads\mask_2057.tif
reference: D:\Data\UOG_2057\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2222
output_path: data\chunks\DRGB_INF\2222
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: C:\Users\danie\OneDrive - University of Cape Town\Uploads\mask_2222.tif
reference: D:\Data\UOG_2222\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2227
output_path: data\chunks\DRGB_INF\2227
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: D:\Data\UOG_2227\mask_2227.tif
reference: D:\Data\UOG_2227\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2228
output_path: data\chunks\DRGB_INF\2228
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: D:\Data\UOG_2228\mask_2228.tif
reference: D:\Data\UOG_2228\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_1724
output_path: data\chunks\DRGB_INF\1724
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: D:\Data\UOG_1724\mask_1724.tif
reference: D:\Data\UOG_1724\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2240
output_path: data\chunks\DRGB_INF\2240
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: D:\Data\UOG_2240\mask_2240.tif
reference: D:\Data\UOG_2240\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5
---
path: D:\Data\UOG_2848
output_path: data\chunks\DRGB_INF\2848
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1
  -
    name: orthos\export-data\orthomosaic_visible.tif
    dimensions: 3
mask: D:\Data\UOG_2848\mask_2848.tif
reference: D:\Data\UOG_2848\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.0
scale_ratio: 0.5