path: F:\Data\UOG_1676
output_path: data\chunks\D_80\1676
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_1676-new.tif
reference: F:\Data\UOG_1676\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_1996
output_path: data\chunks\D_80\1996
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_1996-2.tif
reference: F:\Data\UOG_1996\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_1883
output_path: data\chunks\D_80\1883
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_1883-2.tif
reference: F:\Data\UOG_1883\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2057
output_path: data\chunks\D_80\2057
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_2057-2.tif
reference: F:\Data\UOG_2057\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2222
output_path: data\chunks\D_80\2222
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_2222.tif
reference: F:\Data\UOG_2222\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2227
output_path: data\chunks\D_80\2227
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: C:\Users\Daniel\OneDrive - University of Cape Town\Uploads\mask_2227-2.tif
reference: F:\Data\UOG_2227\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2228
output_path: data\chunks\D_80\2228
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: F:\Data\UOG_2228\mask_2228.tif
reference: F:\Data\UOG_2228\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2240
output_path: data\chunks\D_80\2240
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: F:\Data\UOG_2240\mask_2240.tif
reference: F:\Data\UOG_2240\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_2848
output_path: data\chunks\D_80\2848
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: F:\Data\UOG_2848\mask_2848.tif
reference: F:\Data\UOG_2848\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5
---
path: F:\Data\UOG_1724
output_path: data\chunks\D_80\1724
files:
  -
    name: orthos\export-data\dem_full.tif
    dimensions: 1

mask: F:\Data\UOG_1724\mask_1724.tif
reference: F:\Data\UOG_1724\orthos\data-analysis\reg.tif
chunk_size: 144
chunk_overlap: 0
anomaly_threshold: 0.8
scale_ratio: 0.5