data_path: data/chunks/DRGB_80_RAW/
meta_path: data/chunks/DRGB_80_RAW/metadata/
log_path: logs/proj_optim_weights.txt
resize_x: 256
resize_y: 256
channels: 3

model_path: checkpoints/RD4SAD-97.65.pth
architecture: "wide_resnet50_2"
bn_attention: False

loss_weights: [1.0, 1.0, 1.0]
score_weight: 0.0

proj_loss_weight: 0.758175413875071
ssot_weight: 0.015096731092610782
contrast_weight: 0.9872387127026788
reconstruct_weight: 0.6513426603306253

num_epochs: 30
batch_size: 32
proj_lr: 0.001
distill_lr: 0.005
proj_lr_factor: 0.25
distill_lr_factor: 0.25
beta1_proj: 0.5
beta2_proj: 0.999
beta1_distill: 0.5
beta2_distill: 0.999