data_path: data/chunks/DRGB_80v2/
meta_path: data/chunks/DRGB_80v2/metadata/
log_path: logs/proj.txt
resize_x: 256
resize_y: 256
channels: 3

model_path: checkpoints/RD_proj.pth
architecture: "wide_resnet50_2"
bn_attention: CBAM

loss_weights: [0.82, 0.92, 1.44]
score_weight: 0.2

proj_loss_weight: 0.2
contrast_weight: 0.1
reconstruct_weight: 0.01

num_epochs: 100
batch_size: 16
proj_lr: 0.001
distill_lr: 0.005
proj_lr_factor: 0.333
distill_lr_factor: 0.333
beta1_proj: 0.98
beta2_proj: 0.999
beta1_distill: 0.98
beta2_distill: 0.999