data_path: data/chunks/DRGB_INF2/
meta_path: data/chunks/DRGB_INF2/metadata/
resize_x: 256
resize_y: 256
channels: 3

model_type: RDProj
model_path: checkpoints/RD4SAD-97.65.pth
architecture: "wide_resnet50_2"
bn_attention: False
score_weight: 0
feature_weights: [1.0, 1.0, 1.0]

# classifier params
method: ISO_FOREST
threshold: 3.5        # for z stat
contamination: 0.05   # for isolation forest
forest_threshold: 8  # for isolation forest
eps: 0.1              # for DBSCAN
min_samples: 10       # for DBSCAN
min_score: 0.5        # for DBSCAN