data_path: data/chunks/D_80/
meta_path: data/chunks/D_80/metadata/
log_path: logs/efficientv1.txt
resize_x: 256
resize_y: 256
channels: 1
norm_choice: IMAGE_NET
flip: 0.3
degrees: 5
crop_min: 0.9
noise_factor: 0.05

model_path: checkpoints/model.pth
architecture: "wide_resnet50_2"
bn_attention: True
loss_weights: [1.3, 0.8, 0.8]

score_weights: [0.7, 0.3]
loss_weight_score: False
score_mode: a

optimizer: adam
loss_function: cosine

num_epochs: 6
batch_size: 32
learning_rate: 0.0069
lr_factor: 0.5
weight_decay: 0.0000005
beta1: 0.9856991576085923
beta2: 0.9907935289246718