data_path: data/chunks/DNRED/
meta_path: data/chunks/DNRED/metadata/
log_path: logs/new.txt
resize_x: 256
resize_y: 256
channels: 3
norm_choice: IMAGE_NET
flip: 0.3
crop_min: 0.85
noise_factor: 0.0

model_path: checkpoints/model.pth
architecture: "wide_resnet50_2"
bn_attention: False
loss_weights: [0.95, 0.8, 0.67]

score_weights: [0.42, 0.58]
score_mode: a

optimizer: adam
loss_function: cosine
mse_weight: 0.2

num_epochs: 100
batch_size: 32
learning_rate: 0.0069
lr_factor: 0.457
patience: 2
weight_decay: 0.0000005
beta1: 0.9856991576085923
beta2: 0.9907935289246718
momentum: 0.0001