data_path: data/chunks/D_80/
meta_path: data/chunks/D_80/metadata/
log_path: logs/new.txt
resize_x: 256
resize_y: 256
channels: 1
flip: 0.3
crop_min: 0.9
norm_choice: "IMAGE_NET"

model_path: checkpoints/RD.pth
architecture: "wide_resnet50_2"
bn_attention: SE
optimizer: adam

loss_weights: [0.95, 0.8, 0.67]
score_weights: [0.42, 0.58]

num_epochs: 100
batch_size: 32
learning_rate: 0.0069
lr_factor: 0.333
beta1: 0.9856991576085923
beta2: 0.9907935289246718