data_path: PRE_PROCESS/DATA/PATCHES/INF_DEM_172/
meta_path_train: PRE_PROCESS/DATA/PATCHES/INF_DEM_172/metadata/train_metadata.json
meta_path_test: PRE_PROCESS/DATA/PATCHES/INF_DEM_172/metadata/all_metadata.json
resize_x: 256
resize_y: 256
channels: 2

model_checkpoint: checkpoints/DEM_50_172_trial132.pth   # use for first time running inference
json_checkpoint: RD_DEM_50_172_trial132-0.json               # use for subsequent runs (results saved to json for faster tuning and experimenting)
# relevent model parameters for inference
architecture: "wide_resnet50_2"
bn_attention: False
feature_weights: [0.6338435151392628, 0.5214932144824888, 1.4296368536660933]
#feature_weights: [1, 1, 1]
score_weight: 0.9849566843283396